// import './debounce'
// import './throttle'
// import './objectCreate'
// import './instanceof'
// import './new'
// import './bind-call-apply'
// import './typeof'
// import './curry'
// import './ajax'
// import './reactive'
// import './promise'
// import './clone'
// import './lazyMan'
// import './setInterval'
// import './v-model'
// import './array-sort'
// import './eventBus'
// import './compose'
// import './array-basic'
// import './inherit'
// import './scheduler'
// import './deepClone'
// import "./lazyManWithPromise.ts"
// import "./sort-version.ts"
// import "./LRU.ts"
// import "./dom2json.ts"
// import "./object-is.ts"
// import "./renderDom.ts"
// import "./compile-template.ts"
// import "./flatten.ts"
// import "./bigNum.ts"
// import "./listToTree.ts"
// import "./treeToList.ts"
// import "./arraySort.ts"
// import "./binary-search.ts"
// import "./averageTimes.ts"
// import "./megerSortArray"
// import "./threeSum.ts"
// import "./validPalindrome.ts"
// import "./wordDictionary.ts"
// import "./myAtoi.ts"
// import "./mergeTwoLists.ts"
// import "./deleteDuplicates.ts"
// import "./noRepeatListNode.ts"
// import "./removeNthFromEnd.ts"
// import "./reverseList.ts"
// import "./reverseBetween.ts"
// import "./hasCycle.ts"
// import "./isValid.ts"
// import "./dailyTemperatures.ts"
// import "./MinStack.ts"
// import "./insertIntoBST"
import "./deleteNode.ts"