// import './debounce'
// import './throttle'
// import './objectCreate'
// import './instanceof'
// import './new'
// import './bind-call-apply'
// import './typeof'
// import './curry'
// import './ajax'
// import './reactive'
// import './promise'
// import './clone'
// import './lazyMan'
// import './setInterval'
// import './v-model'
// import './array-sort'
// import './eventBus'
// import './compose'
// import './array-basic'
import './inherit'

